### ISSUE TITLE
Support publishing maven packages to GitHub packages

### ISSUE THREAD

**Issue by jsteinich** [aws/jsii-release#11]
This could be done by adding parallel options, but I think it makes the most sense to just add additional options that also apply to maven central with sensible defaults.

- MAVEN_SERVER_ID : used in maven settings for credential lookup, defaults to `ossrh`
- MAVEN_REPOSITORY_URL: used as the deployment repository. Not used for maven central

MAVEN_STAGING_PROFILE_ID would no longer be required when not using maven central
Signing is also not required for other repositories.

I don't believe the nexus staging plugin works for non-nexus base repositories, but I'm not very familiar with it.
I believe you can deploy to nexus without using it, but it's probably safer to have an alternate code flow that just uses the default maven deploy plugin.

This method should also make it possible to support CodeArtifact as was requested in #10

**Comment by jsteinich** [comment]
I'm happy to help once the direction is agreed upon, although most of my experience with publishing Java packages is with gradle.

**Comment by eladb** [comment]
Sounds like a reasonable direction
