### ISSUE TITLE
go: tags should include module name

### ISSUE THREAD

**Issue by eladb** [aws/jsii-release#26]
For example, for `github.com/aws/constructs-go`, Instead of `v3.3.1` the tag should be `constructs/v3.3.1`. 

This technically allows different modules in the same repo to be tagged with different versions.

Reference: https://research.swtch.com/vgo-module#multiple-module_repositories

> In the major subdirectory convention, v2/ contains the module “my/thing/v2”. A natural extension is to allow subdirectories not named for major versions. For example, we could add a blue/ subdirectory that contains the module “my/thing/blue”, confirmed by a blue/go.mod file with that module path. In this case, the source control commit tags addressing that module would take the form blue/v1.x.x. Similarly, the tag blue/v2.x.x would address the blue/v2/ subdirectory. The existence of the blue/go.mod file excludes the blue/ tree from the outer my/thing module.

**Comment by iliapolo** [comment]
Resolved by https://github.com/aws/jsii-release/pull/27
